export type SiteCustomerMapping = {
  state: string;
  custCode: string;
  custName: string;
  stateCode: string;
  taxEnv: string;
};

export const SITE_CUSTOMER_MAPPING: Record<
  string,
  readonly SiteCustomerMapping[]
> = {
  WM0B6: [
    {
      state: "ASSAM",
      custCode: "WCAMF00019",
      custName: "FBA-KOL-A6-ASSAM-NUT",
      stateCode: "AM",
      taxEnv: "SGST01",
    },
    {
      state: "ANDAMAN & NICOBAR ISLANDS",
      custCode: "WCANF00011",
      custName: "FBA-KOL-A6-ANDAMAN AND NICOBAR ISLANDS-NUT",
      stateCode: "AN",
      taxEnv: "SGST01",
    },
    {
      state: "ANDHRA PRADESH",
      custCode: "WCAPF00014",
      custName: "FBA-KOL-A6-ANDHRA PRADESH-NUT",
      stateCode: "AP",
      taxEnv: "SGST01",
    },
    {
      state: "ARUNACHAL PRADESH",
      custCode: "WCARF00012",
      custName: "FBA-KOL-A6-ARUNACHAL PRADESH-NUT",
      stateCode: "AR",
      taxEnv: "SGST01",
    },
    {
      state: "BIHAR",
      custCode: "WCBHF00016",
      custName: "FBA-KOL-A6-BIHAR-NUT",
      stateCode: "BH",
      taxEnv: "SGST01",
    },
    {
      state: "CHHATTISGARH",
      custCode: "WCCHF00013",
      custName: "FBA-KOL-A6-CHATTISGARH-NUT",
      stateCode: "CH",
      taxEnv: "SGST01",
    },
    {
      state: "CHANDIGARH",
      custCode: "WCCNF00012",
      custName: "FBA-KOL-A6-CHANDIGARH-NUT",
      stateCode: "CN",
      taxEnv: "SGST01",
    },
    {
      state: "DAMAN & DIU",
      custCode: "WCDDF00012",
      custName: "FBA-KOL-A6-DAMAN & DIU-NUT",
      stateCode: "DD",
      taxEnv: "SGST01",
    },
    {
      state: "DADRA AND NAGAR HAVELI AND DAMAN AND DIU",
      custCode: "WCDHF00012",
      custName: "FBA-KOL-A6-DADRA & NAGAR HAVELI & DAMAN & DIU-NUT",
      stateCode: "DH",
      taxEnv: "SGST01",
    },
    {
      state: "DELHI",
      custCode: "WCDLF00027",
      custName: "FBA-KOL-A6-DELHI-NUT",
      stateCode: "DL",
      taxEnv: "SGST01",
    },
    {
      state: "GUJARAT",
      custCode: "WCGJF00016",
      custName: "FBA-KOL-A6-GUJARAT-NUT",
      stateCode: "GJ",
      taxEnv: "SGST01",
    },
    {
      state: "GOA",
      custCode: "WCGOF00013",
      custName: "FBA-KOL-A6-GOA-NUT",
      stateCode: "GO",
      taxEnv: "SGST01",
    },
    {
      state: "HIMACHAL PRADESH",
      custCode: "WCHPF00013",
      custName: "FBA-KOL-A6-HIMACHAL PRADESH-NUT",
      stateCode: "HP",
      taxEnv: "SGST01",
    },
    {
      state: "HARYANA",
      custCode: "WCHRF00024",
      custName: "FBA-KOL-A6-HARYANA-NUT",
      stateCode: "HR",
      taxEnv: "SGST01",
    },
    {
      state: "JHARKHAND",
      custCode: "WCJHF00017",
      custName: "FBA-KOL-A6-JHARKHAND-NUT",
      stateCode: "JH",
      taxEnv: "SGST01",
    },
    {
      state: "JAMMU & KASHMIR",
      custCode: "WCJKF00023",
      custName: "FBA-KOL-A6-JAMMU AND KASHMIR-NUT",
      stateCode: "JK",
      taxEnv: "SGST01",
    },
    {
      state: "JAMMU & KASHMIR",
      custCode: "WCJKF00024",
      custName: "FBA-KOL-A6-LADAKH-NUT",
      stateCode: "JK",
      taxEnv: "SGST01",
    },
    {
      state: "KERALA",
      custCode: "WCKRF00025",
      custName: "FBA-KOL-A6-KERALA-NUT",
      stateCode: "KR",
      taxEnv: "SGST01",
    },
    {
      state: "KARNATAKA",
      custCode: "WCKTF00030",
      custName: "FBA-KOL-A6-KARNATAKA-NUT",
      stateCode: "KT",
      taxEnv: "SGST01",
    },
    {
      state: "LAKSHADWEEPISLAND",
      custCode: "WCLDF00012",
      custName: "FBA-KOL-A6-LAKSHADWEEP ISLANDS-NUT",
      stateCode: "LD",
      taxEnv: "SGST01",
    },
    {
      state: "MEGHALAYA",
      custCode: "WCMGF00013",
      custName: "FBA-KOL-A6-MEGHALAYA-NUT",
      stateCode: "MG",
      taxEnv: "SGST01",
    },
    {
      state: "MAHARASHTRA",
      custCode: "WCMHF00025",
      custName: "FBA-KOL-A6-MAHARASHTRA-NUT",
      stateCode: "MH",
      taxEnv: "SGST01",
    },
    {
      state: "MANIPUR",
      custCode: "WCMNF00015",
      custName: "FBA-KOL-A6-MANIPUR-NUT",
      stateCode: "MN",
      taxEnv: "SGST01",
    },
    {
      state: "MADHYA PRADESH",
      custCode: "WCMPF00018",
      custName: "FBA-KOL-A6-MADHYA PRADESH-NUT",
      stateCode: "MP",
      taxEnv: "SGST01",
    },
    {
      state: "MIZORAM",
      custCode: "WCMZF00013",
      custName: "FBA-KOL-A6-MIZORAM-NUT",
      stateCode: "MZ",
      taxEnv: "SGST01",
    },
    {
      state: "NAGALAND",
      custCode: "WCNGF00013",
      custName: "FBA-KOL-A6-NAGALAND-NUT",
      stateCode: "NG",
      taxEnv: "SGST01",
    },
    {
      state: "ODISHA",
      custCode: "WCORF00016",
      custName: "FBA-KOL-A6-ODISHA-NUT",
      stateCode: "OR",
      taxEnv: "SGST01",
    },
    {
      state: "PUNJAB",
      custCode: "WCPJF00019",
      custName: "FBA-KOL-A6-PUNJAB-NUT",
      stateCode: "PJ",
      taxEnv: "SGST01",
    },
    {
      state: "PUDUCHERRY",
      custCode: "WCPOF00014",
      custName: "FBA-KOL-A6-PONDICHERRY-NUT",
      stateCode: "PO",
      taxEnv: "SGST01",
    },
    {
      state: "RAJASTHAN",
      custCode: "WCRJF00018",
      custName: "FBA-KOL-A6-RAJASTHAN-NUT",
      stateCode: "RJ",
      taxEnv: "SGST01",
    },
    {
      state: "SIKKIM",
      custCode: "WCSKF00013",
      custName: "FBA-KOL-A6-SIKKIM-NUT",
      stateCode: "SK",
      taxEnv: "SGST01",
    },
    {
      state: "TELANGANA",
      custCode: "WCTGF00017",
      custName: "FBA-KOL-A6-TELANGANA-NUT",
      stateCode: "TG",
      taxEnv: "SGST01",
    },
    {
      state: "TAMIL NADU",
      custCode: "WCTNF00021",
      custName: "FBA-KOL-A6-TAMIL NADU-NUT",
      stateCode: "TN",
      taxEnv: "SGST01",
    },
    {
      state: "TRIPURA",
      custCode: "WCTRF00013",
      custName: "FBA-KOL-A6-TRIPURA-NUT",
      stateCode: "TR",
      taxEnv: "SGST01",
    },
    {
      state: "UTTAR PRADESH",
      custCode: "WCUPF00023",
      custName: "FBA-KOL-A6-UTTAR PRADESH-NUT",
      stateCode: "UP",
      taxEnv: "SGST01",
    },
    {
      state: "UTTARAKHAND",
      custCode: "WCURF00015",
      custName: "FBA-KOL-A6-UTTARAKHAND-NUT",
      stateCode: "UR",
      taxEnv: "SGST01",
    },
    {
      state: "WEST BENGAL",
      custCode: "WCWBF00027",
      custName: "FBA-KOL-A6-WEST BENGAL-NUT",
      stateCode: "WB",
      taxEnv: "SWB",
    },
  ],
  WM0B2: [
    {
      state: "ASSAM",
      custCode: "WCAMF00017",
      custName: "FBA-Amazon-B2-MAH-Assam-NUT",
      stateCode: "AM",
      taxEnv: "SGST01",
    },
    {
      state: "ANDAMAN & NICOBAR ISLANDS",
      custCode: "WCANF00009",
      custName: "FBA-Amazon-B2-MAH-Andaman and Nicobar Islands-NUT",
      stateCode: "AN",
      taxEnv: "SGST01",
    },
    {
      state: "ANDHRA PRADESH",
      custCode: "WCAPF00012",
      custName: "FBA-Amazon-B2-MAH-Andhra Pradesh-NUT",
      stateCode: "AP",
      taxEnv: "SGST01",
    },
    {
      state: "ARUNACHAL PRADESH",
      custCode: "WCARF00010",
      custName: "FBA-Amazon-B2-MAH-Arunachal Pradesh-NUT",
      stateCode: "AR",
      taxEnv: "SGST01",
    },
    {
      state: "BIHAR",
      custCode: "WCBHF00014",
      custName: "FBA-Amazon-B2-MAH-Bihar-NUT",
      stateCode: "BH",
      taxEnv: "SGST01",
    },
    {
      state: "CHHATTISGARH",
      custCode: "WCCHF00011",
      custName: "FBA-Amazon-B2-MAH-Chhattisgarh-NUT",
      stateCode: "CH",
      taxEnv: "SGST01",
    },
    {
      state: "CHANDIGARH",
      custCode: "WCCNF00010",
      custName: "FBA-Amazon-B2-MAH-Chandigarh-NUT",
      stateCode: "CN",
      taxEnv: "SGST01",
    },
    {
      state: "DAMAN & DIU",
      custCode: "WCDDF00010",
      custName: "FBA-Amazon-B2-MAH-Daman & Diu-NUT",
      stateCode: "DD",
      taxEnv: "SGST01",
    },
    {
      state: "DADRA AND NAGAR HAVELI AND DAMAN AND DIU",
      custCode: "WCDHF00010",
      custName: "FBA-Amazon-B2-MAH-Dadra & Nagar Haveli and Daman & Diu-NUT",
      stateCode: "DH",
      taxEnv: "SGST01",
    },
    {
      state: "DELHI",
      custCode: "WCDLF00025",
      custName: "FBA-Amazon-B2-MAH-Delhi-NUT",
      stateCode: "DL",
      taxEnv: "SGST01",
    },
    {
      state: "GUJARAT",
      custCode: "WCGJF00014",
      custName: "FBA-Amazon-B2-MAH-Gujarat-NUT",
      stateCode: "GJ",
      taxEnv: "SGST01",
    },
    {
      state: "GOA",
      custCode: "WCGOF00011",
      custName: "FBA-Amazon-B2-MAH-Goa-NUT",
      stateCode: "GO",
      taxEnv: "SGST01",
    },
    {
      state: "HIMACHAL PRADESH",
      custCode: "WCHPF00011",
      custName: "FBA-Amazon-B2-MAH-Himachal Pradesh-NUT",
      stateCode: "HP",
      taxEnv: "SGST01",
    },
    {
      state: "HARYANA",
      custCode: "WCHRF00022",
      custName: "FBA-Amazon-B2-MAH-Haryana-NUT",
      stateCode: "HR",
      taxEnv: "SGST01",
    },
    {
      state: "JHARKHAND",
      custCode: "WCJHF00015",
      custName: "FBA-Amazon-B2-MAH-Jharkhand-NUT",
      stateCode: "JH",
      taxEnv: "SGST01",
    },
    {
      state: "JAMMU & KASHMIR",
      custCode: "WCJKF00019",
      custName: "FBA-Amazon-B2-MAH-Jammu and Kashmir-NUT",
      stateCode: "JK",
      taxEnv: "SGST01",
    },
    {
      state: "KERALA",
      custCode: "WCKRF00023",
      custName: "FBA-Amazon-B2-MAH-Kerala-NUT",
      stateCode: "KR",
      taxEnv: "SGST01",
    },
    {
      state: "KARNATAKA",
      custCode: "WCKTF00028",
      custName: "FBA-Amazon-B2-MAH-Karnataka-NUT",
      stateCode: "KT",
      taxEnv: "SGST01",
    },
    {
      state: "LAKSHADWEEPISLAND",
      custCode: "WCLDF00010",
      custName: "FBA-Amazon-B2-MAH-Lakshadweep Islands-NUT",
      stateCode: "LD",
      taxEnv: "SGST01",
    },
    {
      state: "MEGHALAYA",
      custCode: "WCMGF00011",
      custName: "FBA-Amazon-B2-MAH-Meghalaya-NUT",
      stateCode: "MG",
      taxEnv: "SGST01",
    },
    {
      state: "MAHARASHTRA",
      custCode: "WCMHF00022",
      custName: "FBA-Amazon-B2-MAH-Maharashtra-NUT",
      stateCode: "MH",
      taxEnv: "SMH",
    },
    {
      state: "MANIPUR",
      custCode: "WCMNF00013",
      custName: "FBA-Amazon-B2-MAH-Manipur-NUT",
      stateCode: "MN",
      taxEnv: "SGST01",
    },
    {
      state: "MADHYA PRADESH",
      custCode: "WCMPF00016",
      custName: "FBA-Amazon-B2-MAH-Madhya Pradesh-NUT",
      stateCode: "MP",
      taxEnv: "SGST01",
    },
    {
      state: "MIZORAM",
      custCode: "WCMZF00011",
      custName: "FBA-Amazon-B2-MAH-Mizoram-NUT",
      stateCode: "MZ",
      taxEnv: "SGST01",
    },
    {
      state: "NAGALAND",
      custCode: "WCNGF00011",
      custName: "FBA-Amazon-B2-MAH-Nagaland-NUT",
      stateCode: "NG",
      taxEnv: "SGST01",
    },
    {
      state: "ODISHA",
      custCode: "WCORF00014",
      custName: "FBA-Amazon-B2-MAH-Odisha-NUT",
      stateCode: "OR",
      taxEnv: "SGST01",
    },
    {
      state: "PUNJAB",
      custCode: "WCPJF00017",
      custName: "FBA-Amazon-B2-MAH-Punjab-NUT",
      stateCode: "PJ",
      taxEnv: "SGST01",
    },
    {
      state: "PUDUCHERRY",
      custCode: "WCPOF00012",
      custName: "FBA-Amazon-B2-MAH-Pondicherry-NUT",
      stateCode: "PO",
      taxEnv: "SGST01",
    },
    {
      state: "RAJASTHAN",
      custCode: "WCRJF00016",
      custName: "FBA-Amazon-B2-MAH-Rajasthan-NUT",
      stateCode: "RJ",
      taxEnv: "SGST01",
    },
    {
      state: "SIKKIM",
      custCode: "WCSKF00011",
      custName: "FBA-Amazon-B2-MAH-Sikkim-NUT",
      stateCode: "SK",
      taxEnv: "SGST01",
    },
    {
      state: "TELANGANA",
      custCode: "WCTGF00015",
      custName: "FBA-Amazon-B2-MAH-Telangana-NUT",
      stateCode: "TG",
      taxEnv: "SGST01",
    },
    {
      state: "TAMIL NADU",
      custCode: "WCTNF00019",
      custName: "FBA-Amazon-B2-MAH-Tamil Nadu-NUT",
      stateCode: "TN",
      taxEnv: "SGST01",
    },
    {
      state: "TRIPURA",
      custCode: "WCTRF00011",
      custName: "FBA-Amazon-B2-MAH-Tripura-NUT",
      stateCode: "TR",
      taxEnv: "SGST01",
    },
    {
      state: "UTTAR PRADESH",
      custCode: "WCUPF00021",
      custName: "FBA-Amazon-B2-MAH-Uttar Pradesh-NUT",
      stateCode: "UP",
      taxEnv: "SGST01",
    },
    {
      state: "UTTARAKHAND",
      custCode: "WCURF00013",
      custName: "FBA-Amazon-B2-MAH-Uttarakhand-NUT",
      stateCode: "UR",
      taxEnv: "SGST01",
    },
    {
      state: "WEST BENGAL",
      custCode: "WCWBF00025",
      custName: "FBA-Amazon-B2-MAH-West Bengal-NUT",
      stateCode: "WB",
      taxEnv: "SGST01",
    },
  ],
  WM0A7: [
    {
      state: "ASSAM",
      custCode: "WCAMF00016",
      custName: "",
      stateCode: "AM",
      taxEnv: "SGST01",
    },
    {
      state: "ANDAMAN & NICOBAR ISLANDS",
      custCode: "WCANF00008",
      custName: "",
      stateCode: "AN",
      taxEnv: "SGST01",
    },
    {
      state: "ANDHRA PRADESH",
      custCode: "WCAPF00011",
      custName: "",
      stateCode: "AP",
      taxEnv: "SGST01",
    },
    {
      state: "ARUNACHAL PRADESH",
      custCode: "WCARF00009",
      custName: "",
      stateCode: "AR",
      taxEnv: "SGST01",
    },
    {
      state: "BIHAR",
      custCode: "WCBHF00013",
      custName: "",
      stateCode: "BH",
      taxEnv: "SGST01",
    },
    {
      state: "CHHATTISGARH",
      custCode: "WCCHF00010",
      custName: "",
      stateCode: "CH",
      taxEnv: "SGST01",
    },
    {
      state: "CHANDIGARH",
      custCode: "WCCNF00009",
      custName: "",
      stateCode: "CN",
      taxEnv: "SGST01",
    },
    {
      state: "DADRA AND NAGAR HAVELI AND DAMAN AND DIU",
      custCode: "WCDHF00009",
      custName: "",
      stateCode: "DH",
      taxEnv: "SGST01",
    },
    {
      state: "DELHI",
      custCode: "WCDLF00024",
      custName: "",
      stateCode: "DL",
      taxEnv: "SGST01",
    },
    {
      state: "GUJARAT",
      custCode: "WCGJF00013",
      custName: "",
      stateCode: "GJ",
      taxEnv: "SGST01",
    },
    {
      state: "GOA",
      custCode: "WCGOF00010",
      custName: "",
      stateCode: "GO",
      taxEnv: "SGST01",
    },
    {
      state: "HIMACHAL PRADESH",
      custCode: "WCHPF00010",
      custName: "",
      stateCode: "HP",
      taxEnv: "SGST01",
    },
    {
      state: "HARYANA",
      custCode: "WCHRF00021",
      custName: "",
      stateCode: "HR",
      taxEnv: "SHR",
    },
    {
      state: "JHARKHAND",
      custCode: "WCJHF00014",
      custName: "",
      stateCode: "JH",
      taxEnv: "SGST01",
    },
    {
      state: "JAMMU & KASHMIR",
      custCode: "WCJKF00017",
      custName: "",
      stateCode: "JK",
      taxEnv: "SGST01",
    },
    {
      state: "KERALA",
      custCode: "WCKRF00022",
      custName: "",
      stateCode: "KR",
      taxEnv: "SGST01",
    },
    {
      state: "KARNATAKA",
      custCode: "WCKTF00027",
      custName: "",
      stateCode: "KT",
      taxEnv: "SGST01",
    },
    {
      state: "LAKSHADWEEPISLAND",
      custCode: "WCJKF00018",
      custName: "",
      stateCode: "LD",
      taxEnv: "SGST01",
    },
    {
      state: "MEGHALAYA",
      custCode: "WCMGF00010",
      custName: "",
      stateCode: "MG",
      taxEnv: "SGST01",
    },
    {
      state: "MAHARASHTRA",
      custCode: "WCMHF00021",
      custName: "",
      stateCode: "MH",
      taxEnv: "SGST01",
    },
    {
      state: "MANIPUR",
      custCode: "WCMNF00012",
      custName: "",
      stateCode: "MN",
      taxEnv: "SGST01",
    },
    {
      state: "MADHYA PRADESH",
      custCode: "WCMPF00015",
      custName: "",
      stateCode: "MP",
      taxEnv: "SGST01",
    },
    {
      state: "MIZORAM",
      custCode: "WCMZF00010",
      custName: "",
      stateCode: "MZ",
      taxEnv: "SGST01",
    },
    {
      state: "NAGALAND",
      custCode: "WCNGF00010",
      custName: "",
      stateCode: "NG",
      taxEnv: "SGST01",
    },
    {
      state: "ODISHA",
      custCode: "WCORF00013",
      custName: "",
      stateCode: "OR",
      taxEnv: "SGST01",
    },
    {
      state: "PUNJAB",
      custCode: "WCPJF00016",
      custName: "",
      stateCode: "PJ",
      taxEnv: "SGST01",
    },
    {
      state: "PUDUCHERRY",
      custCode: "WCPOF00011",
      custName: "",
      stateCode: "PO",
      taxEnv: "SGST01",
    },
    {
      state: "RAJASTHAN",
      custCode: "WCRJF00015",
      custName: "",
      stateCode: "RJ",
      taxEnv: "SGST01",
    },
    {
      state: "SIKKIM",
      custCode: "WCSKF00010",
      custName: "",
      stateCode: "SK",
      taxEnv: "SGST01",
    },
    {
      state: "TELANGANA",
      custCode: "WCTGF00014",
      custName: "",
      stateCode: "TG",
      taxEnv: "SGST01",
    },
    {
      state: "TAMIL NADU",
      custCode: "WCTNF00018",
      custName: "",
      stateCode: "TN",
      taxEnv: "SGST01",
    },
    {
      state: "TRIPURA",
      custCode: "WCTRF00010",
      custName: "",
      stateCode: "TR",
      taxEnv: "SGST01",
    },
    {
      state: "UTTAR PRADESH",
      custCode: "WCUPF00020",
      custName: "",
      stateCode: "UP",
      taxEnv: "SGST01",
    },
    {
      state: "UTTARAKHAND",
      custCode: "WCURF00012",
      custName: "",
      stateCode: "UR",
      taxEnv: "SGST01",
    },
    {
      state: "WEST BENGAL",
      custCode: "WCWBF00024",
      custName: "",
      stateCode: "WB",
      taxEnv: "SGST01",
    },
  ],
  WM0C4: [
    {
      state: "ASSAM",
      custCode: "WCAMF00012",
      custName: "FBA-AMAZON-ASSAM-NUT",
      stateCode: "AM",
      taxEnv: "SGST01",
    },
    {
      state: "ANDAMAN & NICOBAR ISLANDS",
      custCode: "WCANF00005",
      custName: "FBA-AMAZON-ANDAMAN AND NICOBAR ISLANDS-NUT",
      stateCode: "AN",
      taxEnv: "SGST01",
    },
    {
      state: "ANDHRA PRADESH",
      custCode: "WCAPF00007",
      custName: "FBA-AMAZON-ANDHRA PRADESH-NUT",
      stateCode: "AP",
      taxEnv: "SGST01",
    },
    {
      state: "ARUNACHAL PRADESH",
      custCode: "WCARF00006",
      custName: "FBA-AMAZON-ARUNACHAL PRADESH-NUT",
      stateCode: "AR",
      taxEnv: "SGST01",
    },
    {
      state: "BIHAR",
      custCode: "WCBHF00009",
      custName: "FBA-AMAZON-BIHAR-NUT",
      stateCode: "BH",
      taxEnv: "SGST01",
    },
    {
      state: "CHHATTISGARH",
      custCode: "WCCHF00006",
      custName: "FBA-AMAZON-CHATTISGARH-NUT",
      stateCode: "CH",
      taxEnv: "SGST01",
    },
    {
      state: "CHANDIGARH",
      custCode: "WCCNF00006",
      custName: "FBA-AMAZON-CHANDIGARH-NUT",
      stateCode: "CN",
      taxEnv: "SGST01",
    },
    {
      state: "DAMAN & DIU",
      custCode: "WCDDF00006",
      custName: "FBA-AMAZON-DAMAN & DIU-NUT",
      stateCode: "DD",
      taxEnv: "SGST01",
    },
    {
      state: "DADRA AND NAGAR HAVELI AND DAMAN AND DIU",
      custCode: "WCDHF00006",
      custName: "FBA-AMAZON-DADRA & NAGAR HAVELI-NUT",
      stateCode: "DH",
      taxEnv: "SGST01",
    },
    {
      state: "DELHI",
      custCode: "WCDLF00016",
      custName: "FBA-AMAZON-DELHI-NUT",
      stateCode: "DL",
      taxEnv: "SDL",
    },
    {
      state: "GUJARAT",
      custCode: "WCGJF00009",
      custName: "FBA-AMAZON-GUJARAT-NUT",
      stateCode: "GJ",
      taxEnv: "SGST01",
    },
    {
      state: "GOA",
      custCode: "WCGOF00007",
      custName: "FBA-AMAZON-GOA-NUT",
      stateCode: "GO",
      taxEnv: "SGST01",
    },
    {
      state: "HIMACHAL PRADESH",
      custCode: "WCHPF00007",
      custName: "FBA-AMAZON-HIMACHAL PRADESH-NUT",
      stateCode: "HP",
      taxEnv: "SGST01",
    },
    {
      state: "HARYANA",
      custCode: "WCHRF00016",
      custName: "FBA-AMAZON-HARYANA-NUT",
      stateCode: "HR",
      taxEnv: "SGST01",
    },
    {
      state: "JHARKHAND",
      custCode: "WCJHF00011",
      custName: "FBA-AMAZON-JHARKHAND-NUT",
      stateCode: "JH",
      taxEnv: "SGST01",
    },
    {
      state: "JAMMU & KASHMIR",
      custCode: "WCJKF00010",
      custName: "FBA-AMAZON-JAMMU AND KASHMIR-NUT",
      stateCode: "JK",
      taxEnv: "SGST01",
    },
    {
      state: "JAMMU & KASHMIR",
      custCode: "WCJKF00011",
      custName: "FBA-AMAZON-LADAKH-NUT",
      stateCode: "JK",
      taxEnv: "SGST01",
    },
    {
      state: "KERALA",
      custCode: "WCKRF00018",
      custName: "FBA-AMAZON-KERALA-NUT",
      stateCode: "KR",
      taxEnv: "SGST01",
    },
    {
      state: "KARNATAKA",
      custCode: "WCKTF00017",
      custName: "FBA-AMAZON-KARNATAKA-NUT",
      stateCode: "KT",
      taxEnv: "SGST01",
    },
    {
      state: "LAKSHADWEEPISLAND",
      custCode: "WCLDF00006",
      custName: "FBA-AMAZON-LAKSHADWEEP ISLANDS-NUT",
      stateCode: "LD",
      taxEnv: "SGST01",
    },
    {
      state: "MEGHALAYA",
      custCode: "WCMGF00007",
      custName: "FBA-AMAZON-MEGHALAYA-NUT",
      stateCode: "MG",
      taxEnv: "SGST01",
    },
    {
      state: "MAHARASHTRA",
      custCode: "WCMHF00015",
      custName: "FBA-AMAZON-MAHARASHTRA-NUT",
      stateCode: "MH",
      taxEnv: "SGST01",
    },
    {
      state: "MANIPUR",
      custCode: "WCMNF00009",
      custName: "FBA-AMAZON-MANIPUR-NUT",
      stateCode: "MN",
      taxEnv: "SGST01",
    },
    {
      state: "MADHYA PRADESH",
      custCode: "WCMPF00011",
      custName: "FBA-AMAZON-MADHYA PRADESH-NUT",
      stateCode: "MP",
      taxEnv: "SGST01",
    },
    {
      state: "MIZORAM",
      custCode: "WCMZF00007",
      custName: "FBA-AMAZON-MIZORAM-NUT",
      stateCode: "MZ",
      taxEnv: "SGST01",
    },
    {
      state: "NAGALAND",
      custCode: "WCNGF00007",
      custName: "FBA-AMAZON-NAGALAND-NUT",
      stateCode: "NG",
      taxEnv: "SGST01",
    },
    {
      state: "ODISHA",
      custCode: "WCORF00009",
      custName: "FBA-AMAZON-ODISHA-NUT",
      stateCode: "OR",
      taxEnv: "SGST01",
    },
    {
      state: "PUNJAB",
      custCode: "WCPJF00012",
      custName: "FBA-AMAZON-PUNJAB-NUT",
      stateCode: "PJ",
      taxEnv: "SGST01",
    },
    {
      state: "PUDUCHERRY",
      custCode: "WCPOF00007",
      custName: "FBA-AMAZON-PONDICHERRY-NUT",
      stateCode: "PO",
      taxEnv: "SGST01",
    },
    {
      state: "RAJASTHAN",
      custCode: "WCRJF00011",
      custName: "FBA-AMAZON-RAJASTHAN-NUT",
      stateCode: "RJ",
      taxEnv: "SGST01",
    },
    {
      state: "SIKKIM",
      custCode: "WCSKF00007",
      custName: "FBA-AMAZON-SIKKIM-NUT",
      stateCode: "SK",
      taxEnv: "SGST01",
    },
    {
      state: "TELANGANA",
      custCode: "WCTGF00009",
      custName: "FBA-AMAZON-TELANGANA-NUT",
      stateCode: "TG",
      taxEnv: "SGST01",
    },
    {
      state: "TAMIL NADU",
      custCode: "WCTNF00014",
      custName: "FBA-AMAZON-TAMILNADU-NUT",
      stateCode: "TN",
      taxEnv: "SGST01",
    },
    {
      state: "TRIPURA",
      custCode: "WCTRF00007",
      custName: "FBA-AMAZON-TRIPURA-NUT",
      stateCode: "TR",
      taxEnv: "SGST01",
    },
    {
      state: "UTTAR PRADESH",
      custCode: "WCUPF00015",
      custName: "FBA-AMAZON-UTTAR PRADESH-NUT",
      stateCode: "UP",
      taxEnv: "SGST01",
    },
    {
      state: "UTTARAKHAND",
      custCode: "WCURF00008",
      custName: "FBA-AMAZON-UTTARAKHAND-NUT",
      stateCode: "UR",
      taxEnv: "SGST01",
    },
    {
      state: "WEST BENGAL",
      custCode: "WCWBF00019",
      custName: "FBA-AMAZON-WEST BENGAL-NUT",
      stateCode: "WB",
      taxEnv: "SGST01",
    },
  ],
  WM0A6: [
    {
      state: "ASSAM",
      custCode: "WCAMF00014",
      custName: "FBA-KOL-A6-ASSAM-NUT",
      stateCode: "AM",
      taxEnv: "SGST01",
    },
    {
      state: "ANDAMAN & NICOBAR ISLANDS",
      custCode: "WCANF00007",
      custName: "FBA-KOL-A6-ANDAMAN AND NICOBAR ISLANDS-NUT",
      stateCode: "AN",
      taxEnv: "SGST01",
    },
    {
      state: "ANDHRA PRADESH",
      custCode: "WCAPF00009",
      custName: "FBA-KOL-A6-ANDHRA PRADESH-NUT",
      stateCode: "AP",
      taxEnv: "SGST01",
    },
    {
      state: "ARUNACHAL PRADESH",
      custCode: "WCARF00008",
      custName: "FBA-KOL-A6-ARUNACHAL PRADESH-NUT",
      stateCode: "AR",
      taxEnv: "SGST01",
    },
    {
      state: "BIHAR",
      custCode: "WCBHF00011",
      custName: "FBA-KOL-A6-BIHAR-NUT",
      stateCode: "BH",
      taxEnv: "SGST01",
    },
    {
      state: "CHHATTISGARH",
      custCode: "WCCHF00008",
      custName: "FBA-KOL-A6-CHHATTISGARH-NUT",
      stateCode: "CH",
      taxEnv: "SGST01",
    },
    {
      state: "CHANDIGARH",
      custCode: "WCCNF00008",
      custName: "FBA-KOL-A6-CHANDIGARH-NUT",
      stateCode: "CN",
      taxEnv: "SGST01",
    },
    {
      state: "DAMAN & DIU",
      custCode: "WCDDF00008",
      custName: "FBA-KOL-A6-DAMAN & DIU-NUT",
      stateCode: "DD",
      taxEnv: "SGST01",
    },
    {
      state: "DADRA AND NAGAR HAVELI AND DAMAN AND DIU",
      custCode: "WCDHF00008",
      custName: "FBA-KOL-A6-DADRA & NAGAR HAVELI & DAMAN & DIU-NUT",
      stateCode: "DH",
      taxEnv: "SGST01",
    },
    {
      state: "DELHI",
      custCode: "WCDLF00019",
      custName: "FBA-KOL-A6-DELHI-NUT",
      stateCode: "DL",
      taxEnv: "SGST01",
    },
    {
      state: "GUJARAT",
      custCode: "WCGJF00011",
      custName: "FBA-KOL-A6-GUJARAT-NUT",
      stateCode: "GJ",
      taxEnv: "SGST01",
    },
    {
      state: "GOA",
      custCode: "WCGOF00009",
      custName: "FBA-KOL-A6-GOA-NUT",
      stateCode: "GO",
      taxEnv: "SGST01",
    },
    {
      state: "HIMACHAL PRADESH",
      custCode: "WCHPF00009",
      custName: "FBA-KOL-A6-HIMACHAL PRADESH-NUT",
      stateCode: "HP",
      taxEnv: "SGST01",
    },
    {
      state: "HARYANA",
      custCode: "WCHRF00018",
      custName: "FBA-KOL-A6-HARYANA-NUT",
      stateCode: "HR",
      taxEnv: "SGST01",
    },
    {
      state: "JHARKHAND",
      custCode: "WCJHF00013",
      custName: "FBA-KOL-A6-JHARKHAND-NUT",
      stateCode: "JH",
      taxEnv: "SGST01",
    },
    {
      state: "JAMMU & KASHMIR",
      custCode: "WCJKF00014",
      custName: "FBA-KOL-A6-JAMMU AND KASHMIR-NUT",
      stateCode: "JK",
      taxEnv: "SGST01",
    },
    {
      state: "JAMMU & KASHMIR",
      custCode: "WCJKF00015",
      custName: "FBA-KOL-A6-LADAKH-NUT",
      stateCode: "JK",
      taxEnv: "SGST01",
    },
    {
      state: "KERALA",
      custCode: "WCKRF00020",
      custName: "FBA-KOL-A6-KERALA-NUT",
      stateCode: "KR",
      taxEnv: "SGST01",
    },
    {
      state: "KARNATAKA",
      custCode: "WCKTF00020",
      custName: "FBA-KOL-A6-KARNATAKA-NUT",
      stateCode: "KT",
      taxEnv: "SGST01",
    },
    {
      state: "LAKSHADWEEPISLAND",
      custCode: "WCLDF00008",
      custName: "FBA-KOL-A6-LAKSHADWEEP ISLANDS-NUT",
      stateCode: "LD",
      taxEnv: "SGST01",
    },
    {
      state: "MEGHALAYA",
      custCode: "WCMGF00009",
      custName: "FBA-KOL-A6-MEGHALAYA-NUT",
      stateCode: "MG",
      taxEnv: "SGST01",
    },
    {
      state: "MAHARASHTRA",
      custCode: "WCMHF00017",
      custName: "FBA-KOL-A6-MAHARASHTRA-NUT",
      stateCode: "MH",
      taxEnv: "SGST01",
    },
    {
      state: "MANIPUR",
      custCode: "WCMNF00011",
      custName: "FBA-KOL-A6-MANIPUR-NUT",
      stateCode: "MN",
      taxEnv: "SGST01",
    },
    {
      state: "MADHYA PRADESH",
      custCode: "WCMPF00013",
      custName: "FBA-KOL-A6-MADHYA PRADESH-NUT",
      stateCode: "MP",
      taxEnv: "SGST01",
    },
    {
      state: "MIZORAM",
      custCode: "WCMZF00009",
      custName: "FBA-KOL-A6-MIZORAM-NUT",
      stateCode: "MZ",
      taxEnv: "SGST01",
    },
    {
      state: "NAGALAND",
      custCode: "WCNGF00009",
      custName: "FBA-KOL-A6-NAGALAND-NUT",
      stateCode: "NG",
      taxEnv: "SGST01",
    },
    {
      state: "ODISHA",
      custCode: "WCORF00011",
      custName: "FBA-KOL-A6-ODISHA-NUT",
      stateCode: "OR",
      taxEnv: "SGST01",
    },
    {
      state: "PUNJAB",
      custCode: "WCPJF00014",
      custName: "FBA-KOL-A6-PUNJAB-NUT",
      stateCode: "PJ",
      taxEnv: "SGST01",
    },
    {
      state: "PUDUCHERRY",
      custCode: "WCPOF00009",
      custName: "FBA-KOL-A6-PONDICHERRY-NUT",
      stateCode: "PO",
      taxEnv: "SGST01",
    },
    {
      state: "RAJASTHAN",
      custCode: "WCRJF00013",
      custName: "FBA-KOL-A6-RAJASTHAN-NUT",
      stateCode: "RJ",
      taxEnv: "SGST01",
    },
    {
      state: "SIKKIM",
      custCode: "WCSKF00009",
      custName: "FBA-KOL-A6-SIKKIM-NUT",
      stateCode: "SK",
      taxEnv: "SGST01",
    },
    {
      state: "TELANGANA",
      custCode: "WCTGF00012",
      custName: "FBA-KOL-A6-TELANGANA-NUT",
      stateCode: "TG",
      taxEnv: "SGST01",
    },
    {
      state: "TAMIL NADU",
      custCode: "WCTNF00016",
      custName: "FBA-KOL-A6-TAMIL NADU-NUT",
      stateCode: "TN",
      taxEnv: "SGST01",
    },
    {
      state: "TRIPURA",
      custCode: "WCTRF00009",
      custName: "FBA-KOL-A6-TRIPURA-NUT",
      stateCode: "TR",
      taxEnv: "SGST01",
    },
    {
      state: "UTTAR PRADESH",
      custCode: "WCUPF00018",
      custName: "FBA-KOL-A6-UTTAR PRADESH-NUT",
      stateCode: "UP",
      taxEnv: "SGST01",
    },
    {
      state: "UTTARAKHAND",
      custCode: "WCURF00010",
      custName: "FBA-KOL-A6-UTTARAKHAND-NUT",
      stateCode: "UR",
      taxEnv: "SGST01",
    },
    {
      state: "WEST BENGAL",
      custCode: "WCWBF00021",
      custName: "FBA-KOL-A6-WEST BENGAL-NUT",
      stateCode: "WB",
      taxEnv: "SWB",
    },
  ],
  WM0A5: [
    {
      state: "ASSAM",
      custCode: "WCAMF00013",
      custName: "FBA-BANGALORE-ASSAM-NUT",
      stateCode: "AM",
      taxEnv: "SGST01",
    },
    {
      state: "ANDAMAN & NICOBAR ISLANDS",
      custCode: "WCANF00006",
      custName: "FBA-BANGALORE-ANDAMAN AND NICOBAR ISLANDS-NUT",
      stateCode: "AN",
      taxEnv: "SGST01",
    },
    {
      state: "ANDHRA PRADESH",
      custCode: "WCAPF00008",
      custName: "FBA-BANGALORE-ANDHRA PRADESH-NUT",
      stateCode: "AP",
      taxEnv: "SGST01",
    },
    {
      state: "ARUNACHAL PRADESH",
      custCode: "WCARF00007",
      custName: "FBA-BANGALORE-ARUNACHAL PRADESH-NUT",
      stateCode: "AR",
      taxEnv: "SGST01",
    },
    {
      state: "BIHAR",
      custCode: "WCBHF00010",
      custName: "FBA-BANGALORE-BIHAR-NUT",
      stateCode: "BH",
      taxEnv: "SGST01",
    },
    {
      state: "CHHATTISGARH",
      custCode: "WCCHF00007",
      custName: "FBA-BANGALORE-CHHATTISGARH-NUT",
      stateCode: "CH",
      taxEnv: "SGST01",
    },
    {
      state: "CHANDIGARH",
      custCode: "WCCNF00007",
      custName: "FBA-BANGALORE-CHANDIGARH-NUT",
      stateCode: "CN",
      taxEnv: "SGST01",
    },
    {
      state: "DADRA AND NAGAR HAVELI AND DAMAN AND DIU",
      custCode: "WCDHF00007",
      custName: "FBA-BANGALORE-DADRA & NAGAR HAVELI AND DAMAN-NUT",
      stateCode: "DH",
      taxEnv: "SGST01",
    },
    {
      state: "DELHI",
      custCode: "WCDLF00018",
      custName: "FBA-BANGALORE-DELHI-NUT",
      stateCode: "DL",
      taxEnv: "SGST01",
    },
    {
      state: "GUJARAT",
      custCode: "WCGJF00010",
      custName: "FBA-BANGALORE-GUJARAT-NUT",
      stateCode: "GJ",
      taxEnv: "SGST01",
    },
    {
      state: "GOA",
      custCode: "WCGOF00008",
      custName: "FBA-BANGALORE-GOA-NUT",
      stateCode: "GO",
      taxEnv: "SGST01",
    },
    {
      state: "HIMACHAL PRADESH",
      custCode: "WCHPF00008",
      custName: "FBA-BANGALORE-HIMACHAL PRADESH-NUT",
      stateCode: "HP",
      taxEnv: "SGST01",
    },
    {
      state: "HARYANA",
      custCode: "WCHRF00017",
      custName: "FBA-BANGALORE-HARYANA-NUT",
      stateCode: "HR",
      taxEnv: "SGST01",
    },
    {
      state: "JHARKHAND",
      custCode: "WCJHF00012",
      custName: "FBA-BANGALORE-JHARKHAND-NUT",
      stateCode: "JH",
      taxEnv: "SGST01",
    },
    {
      state: "JAMMU & KASHMIR",
      custCode: "WCJKF00013",
      custName: "FBA-BANGALORE-JAMMU AND KASHMIR-NUT",
      stateCode: "JK",
      taxEnv: "SGST01",
    },
    {
      state: "JAMMU & KASHMIR",
      custCode: "WCJKF00012",
      custName: "FBA-BANGALORE-LADAKH-NUT",
      stateCode: "JK",
      taxEnv: "SGST01",
    },
    {
      state: "KERALA",
      custCode: "WCKRF00019",
      custName: "FBA-BANGALORE-KERALA-NUT",
      stateCode: "KR",
      taxEnv: "SGST01",
    },
    {
      state: "KARNATAKA",
      custCode: "WCKTF00018",
      custName: "FBA-BANGALORE-KARNATAKA-NUT",
      stateCode: "KT",
      taxEnv: "SKA",
    },
    {
      state: "LAKSHADWEEPISLAND",
      custCode: "WCLDF00007",
      custName: "FBA-BANGALORE-LAKSHADWEEP ISLANDS-NUT",
      stateCode: "LD",
      taxEnv: "SGST01",
    },
    {
      state: "MEGHALAYA",
      custCode: "WCMGF00008",
      custName: "FBA-BANGALORE-MEGHALAYA-NUT",
      stateCode: "MG",
      taxEnv: "SGST01",
    },
    {
      state: "MAHARASHTRA",
      custCode: "WCMHF00016",
      custName: "FBA-BANGALORE-MAHARASHTRA-NUT",
      stateCode: "MH",
      taxEnv: "SGST01",
    },
    {
      state: "MANIPUR",
      custCode: "WCMNF00010",
      custName: "FBA-BANGALORE-MANIPUR-NUT",
      stateCode: "MN",
      taxEnv: "SGST01",
    },
    {
      state: "MADHYA PRADESH",
      custCode: "WCMPF00012",
      custName: "FBA-BANGALORE-MADHYA PRADESH-NUT",
      stateCode: "MP",
      taxEnv: "SGST01",
    },
    {
      state: "MIZORAM",
      custCode: "WCMZF00008",
      custName: "FBA-BANGALORE-MIZORAM-NUT",
      stateCode: "MZ",
      taxEnv: "SGST01",
    },
    {
      state: "NAGALAND",
      custCode: "WCNGF00008",
      custName: "FBA-BANGALORE-NAGALAND-NUT",
      stateCode: "NG",
      taxEnv: "SGST01",
    },
    {
      state: "ODISHA",
      custCode: "WCORF00010",
      custName: "FBA-BANGALORE-ODISHA-NUT",
      stateCode: "OR",
      taxEnv: "SGST01",
    },
    {
      state: "PUNJAB",
      custCode: "WCPJF00013",
      custName: "FBA-BANGALORE-PUNJAB-NUT",
      stateCode: "PJ",
      taxEnv: "SGST01",
    },
    {
      state: "PUDUCHERRY",
      custCode: "WCPOF00008",
      custName: "FBA-BANGALORE-PONDICHERRY-NUT",
      stateCode: "PO",
      taxEnv: "SGST01",
    },
    {
      state: "RAJASTHAN",
      custCode: "WCRJF00012",
      custName: "FBA-BANGALORE-RAJASTHAN-NUT",
      stateCode: "RJ",
      taxEnv: "SGST01",
    },
    {
      state: "SIKKIM",
      custCode: "WCSKF00008",
      custName: "FBA-BANGALORE-SIKKIM-NUT",
      stateCode: "SK",
      taxEnv: "SGST01",
    },
    {
      state: "TELANGANA",
      custCode: "WCTGF00010",
      custName: "FBA-BANGALORE-TELANGANA-NUT",
      stateCode: "TG",
      taxEnv: "SGST01",
    },
    {
      state: "TAMIL NADU",
      custCode: "WCTNF00015",
      custName: "FBA-BANGALORE-TAMIL NADU-NUT",
      stateCode: "TN",
      taxEnv: "SGST01",
    },
    {
      state: "TRIPURA",
      custCode: "WCTRF00008",
      custName: "FBA-BANGALORE-TRIPURA-NUT",
      stateCode: "TR",
      taxEnv: "SGST01",
    },
    {
      state: "UTTAR PRADESH",
      custCode: "WCUPF00016",
      custName: "FBA-BANGALORE-UTTAR PRADESH-NUT",
      stateCode: "UP",
      taxEnv: "SGST01",
    },
    {
      state: "UTTARAKHAND",
      custCode: "WCURF00009",
      custName: "FBA-BANGALORE-UTTARAKHAND-NUT",
      stateCode: "UR",
      taxEnv: "SGST01",
    },
    {
      state: "WEST BENGAL",
      custCode: "WCWBF00020",
      custName: "FBA-BANGALORE-WEST BENGAL-NUT",
      stateCode: "WB",
      taxEnv: "SGST01",
    },
  ],
  WM0B5: [
    {
      state: "ASSAM",
      custCode: "WCAMF00018",
      custName: "FBA-BR-B5-Assam-NUT",
      stateCode: "AM",
      taxEnv: "SGST01",
    },
    {
      state: "ANDAMAN & NICOBAR ISLANDS",
      custCode: "WCANF00010",
      custName: "FBA-BR-B5-Andaman and Nicobar Islands-NUT",
      stateCode: "AN",
      taxEnv: "SGST01",
    },
    {
      state: "ANDHRA PRADESH",
      custCode: "WCAPF00013",
      custName: "FBA-BR-B5-Andhra Pradesh-NUT",
      stateCode: "AP",
      taxEnv: "SGST01",
    },
    {
      state: "ARUNACHAL PRADESH",
      custCode: "WCARF00011",
      custName: "FBA-BR-B5-Arunachal Pradesh-NUT",
      stateCode: "AR",
      taxEnv: "SGST01",
    },
    {
      state: "BIHAR",
      custCode: "WCBHF00015",
      custName: "FBA-BR-B5-Bihar-NUT",
      stateCode: "BH",
      taxEnv: "SGST01",
    },
    {
      state: "CHHATTISGARH",
      custCode: "WCCHF00012",
      custName: "FBA-BR-B5-Chhattisgarh-NUT",
      stateCode: "CH",
      taxEnv: "SGST01",
    },
    {
      state: "CHANDIGARH",
      custCode: "WCCNF00011",
      custName: "FBA-BR-B5-Chandigarh-NUT",
      stateCode: "CN",
      taxEnv: "SGST01",
    },
    {
      state: "DADRA AND NAGAR HAVELI AND DAMAN AND DIU",
      custCode: "WCDHF00011",
      custName: "FBA-BR-B5-Dadra & Nagar Haveli and Daman & Diu-NUT",
      stateCode: "DH",
      taxEnv: "SGST01",
    },
    {
      state: "DELHI",
      custCode: "WCDLF00026",
      custName: "FBA-BR-B5-Delhi-NUT",
      stateCode: "DL",
      taxEnv: "SGST01",
    },
    {
      state: "GUJARAT",
      custCode: "WCGJF00015",
      custName: "FBA-BR-B5-Gujarat-NUT",
      stateCode: "GJ",
      taxEnv: "SGST01",
    },
    {
      state: "GOA",
      custCode: "WCGOF00012",
      custName: "FBA-BR-B5-Goa-NUT",
      stateCode: "GO",
      taxEnv: "SGST01",
    },
    {
      state: "HIMACHAL PRADESH",
      custCode: "WCHPF00012",
      custName: "FBA-BR-B5-Himachal Pradesh-NUT",
      stateCode: "HP",
      taxEnv: "SGST01",
    },
    {
      state: "HARYANA",
      custCode: "WCHRF00023",
      custName: "FBA-BR-B5-Haryana-NUT",
      stateCode: "HR",
      taxEnv: "SGST01",
    },
    {
      state: "JHARKHAND",
      custCode: "WCJHF00016",
      custName: "FBA-BR-B5-Jharkhand-NUT",
      stateCode: "JH",
      taxEnv: "SGST01",
    },
    {
      state: "JAMMU & KASHMIR",
      custCode: "WCJKF00021",
      custName: "FBA-BR-B5-Jammu and Kashmir-NUT",
      stateCode: "JK",
      taxEnv: "SGST01",
    },
    {
      state: "KERALA",
      custCode: "WCKRF00024",
      custName: "FBA-BR-B5-Kerala-NUT",
      stateCode: "KR",
      taxEnv: "SGST01",
    },
    {
      state: "KARNATAKA",
      custCode: "WCKTF00029",
      custName: "FBA-BR-B5-Karnataka-NUT",
      stateCode: "KT",
      taxEnv: "SKA",
    },
    {
      state: "LAKSHADWEEPISLAND",
      custCode: "WCLDF00011",
      custName: "FBA-BR-B5-Lakshadweep Islands-NUT",
      stateCode: "LD",
      taxEnv: "SGST01",
    },
    {
      state: "MEGHALAYA",
      custCode: "WCMGF00012",
      custName: "FBA-BR-B5-Meghalaya-NUT",
      stateCode: "MG",
      taxEnv: "SGST01",
    },
    {
      state: "MAHARASHTRA",
      custCode: "WCMHF00024",
      custName: "FBA-BR-B5-Maharashtra-NUT",
      stateCode: "MH",
      taxEnv: "SGST01",
    },
    {
      state: "MANIPUR",
      custCode: "WCMNF00014",
      custName: "FBA-BR-B5-Manipur-NUT",
      stateCode: "MN",
      taxEnv: "SGST01",
    },
    {
      state: "MADHYA PRADESH",
      custCode: "WCMPF00017",
      custName: "FBA-BR-B5-Madhya Pradesh-NUT",
      stateCode: "MP",
      taxEnv: "SGST01",
    },
    {
      state: "MIZORAM",
      custCode: "WCMZF00012",
      custName: "FBA-BR-B5-Mizoram-NUT",
      stateCode: "MZ",
      taxEnv: "SGST01",
    },
    {
      state: "NAGALAND",
      custCode: "WCNGF00012",
      custName: "FBA-BR-B5-Nagaland-NUT",
      stateCode: "NG",
      taxEnv: "SGST01",
    },
    {
      state: "ODISHA",
      custCode: "WCORF00015",
      custName: "FBA-BR-B5-Odisha-NUT",
      stateCode: "OR",
      taxEnv: "SGST01",
    },
    {
      state: "PUNJAB",
      custCode: "WCPJF00018",
      custName: "FBA-BR-B5-Punjab-NUT",
      stateCode: "PJ",
      taxEnv: "SGST01",
    },
    {
      state: "PUDUCHERRY",
      custCode: "WCPOF00013",
      custName: "FBA-BR-B5-Pondicherry-NUT",
      stateCode: "PO",
      taxEnv: "SGST01",
    },
    {
      state: "RAJASTHAN",
      custCode: "WCRJF00017",
      custName: "FBA-BR-B5-Rajasthan-NUT",
      stateCode: "RJ",
      taxEnv: "SGST01",
    },
    {
      state: "SIKKIM",
      custCode: "WCSKF00012",
      custName: "FBA-BR-B5-Sikkim-NUT",
      stateCode: "SK",
      taxEnv: "SGST01",
    },
    {
      state: "TELANGANA",
      custCode: "WCTGF00016",
      custName: "FBA-BR-B5-Telangana-NUT",
      stateCode: "TG",
      taxEnv: "SGST01",
    },
    {
      state: "TAMIL NADU",
      custCode: "WCTNF00020",
      custName: "FBA-BR-B5-Tamil Nadu-NUT",
      stateCode: "TN",
      taxEnv: "SGST01",
    },
    {
      state: "TRIPURA",
      custCode: "WCTRF00012",
      custName: "FBA-BR-B5-Tripura-NUT",
      stateCode: "TR",
      taxEnv: "SGST01",
    },
    {
      state: "UTTAR PRADESH",
      custCode: "WCUPF00022",
      custName: "FBA-BR-B5-Uttar Pradesh-NUT",
      stateCode: "UP",
      taxEnv: "SGST01",
    },
    {
      state: "UTTARAKHAND",
      custCode: "WCURF00014",
      custName: "FBA-BR-B5-Uttarakhand-NUT",
      stateCode: "UR",
      taxEnv: "SGST01",
    },
    {
      state: "WEST BENGAL",
      custCode: "WCWBF00026",
      custName: "FBA-BR-B5-West Bengal-NUT",
      stateCode: "WB",
      taxEnv: "SGST01",
    },
  ],
} as const;
